service: grupo-sillas-bot

provider:
  name: aws
  runtime: rust
  memorySize: 128
plugins:
  - serverless-rust
package:
  individually: true

custom:
  rust:
    dockerless: true

functions:
  interactionHandler:
    handler: interaction-handler
    environment:
      DISCORD_BOT_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}
      LOL_API_KEY: ${env:LOL_API_KEY}
    events:
      - httpApi: 'POST /interaction'
  asyncMatchesResponderHandler:
    handler: async-matches-responder
    environment:
      INPUT_QUEUE: { Ref: LolMatchesQueue }

resources:
  Resources:
    LolMatchesQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: sqs-matches-commands-queue.fifo
        FifoQueue: true