service: grupo-sillas-bot

provider:
  name: aws
  runtime: rust
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'sqs:ListQueues'
      Resource: '*'
    # Allow functions to write to matches sqs queue
    - Effect: Allow
      Action:
        - 'sqs:SendMessage'
      Resource:
        - Fn::GetAtt: [LolMatchesQueue, Arn]
plugins:
  - serverless-rust
package:
  individually: true

custom:
  rust:
    dockerless: true

functions:
  interactionHandler:
    handler: interaction-handler
    environment:
      DISCORD_BOT_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}
      LOL_API_KEY: ${env:LOL_API_KEY}
      MATCHES_QUEUE_URL: { Ref: LolMatchesQueue }
    events:
      - httpApi: 'POST /interaction'
  asyncMatchesResponderHandler:
    handler: async-matches-responder
    timeout: 60
    environment:
      DISCORD_BOT_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}
      LOL_API_KEY: ${env:LOL_API_KEY}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - LolMatchesQueue
              - Arn

resources:
  Resources:
    LolMatchesQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: sqs-matches-commands-queue.fifo
        FifoQueue: true