service: grupo-sillas-bot

provider:
  name: aws
  runtime: rust
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'sqs:ListQueues'
      Resource: '*'
    # Allow functions to write to matches sqs queue
    - Effect: Allow
      Action:
        - 'sqs:SendMessage'
      Resource:
        - Fn::GetAtt: [LolMatchesQueue, Arn]
    - Effect: Allow
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:PutItem'
    - Resource:
        - Fn::GetAtt: [GrupoSillasBotTable, Arn]
plugins:
  - serverless-rust
  - serverless-dynamodb-autoscaling
package:
  individually: true

custom:
  rust:
    dockerless: true
  capacities:
  - table: GrupoSillasBotTable  # DynamoDB Resource
    read:
      minimum: 5        # Minimum read capacity
      maximum: 10     # Maximum read capacity
      usage: 0.75       # Targeted usage percentage
    write:
      minimum: 1       # Minimum write capacity
      maximum: 10      # Maximum write capacity
      usage: 0.5        # Targeted usage percentage

functions:
  interactionHandler:
    handler: interaction-handler
    environment:
      DISCORD_BOT_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}
      LOL_API_KEY: ${env:LOL_API_KEY}
      MATCHES_QUEUE_URL: { Ref: LolMatchesQueue }
      DYNAMO_TABLE_NAME: GrupoSillasBotTable
    events:
      - httpApi: 'POST /interaction'
  asyncMatchesResponderHandler:
    handler: async-matches-responder
    timeout: 60
    environment:
      DISCORD_BOT_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}
      LOL_API_KEY: ${env:LOL_API_KEY}
      DYNAMO_TABLE_NAME: GrupoSillasBotTable
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - LolMatchesQueue
              - Arn

resources:
  Resources:
    LolMatchesQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: sqs-matches-commands-queue.fifo
        FifoQueue: true
        VisibilityTimeout: 60
    GrupoSillasBotTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: grupoSillasBotTable
        AttributeDefinitions:
          - AttributeName: partitionKey
            AttributeType: S
          - AttributeName: sortKey
            AttributeType: S
        KeySchema:
          - AttributeName: partitionKey
            KeyType: HASH
          - AttributeName: sortKey
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1
