[package]
name = "common"
version = "0.1.0"
authors = ["Gordon Martin"]
edition = "2018"

[dependencies]
serde = { version = "1.0.137",  features = ["derive"] }
serde_json = "1.0.79"
aws-config = "0.15.0"
aws-sdk-dynamodb = "0.15.0"
