on:
  push:
    branches:
      - main

jobs:
  deploy_serverless_stack_job:
    runs-on: ubuntu-latest
    name: Deploys the bot serverless stack
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy step
        id: deploy_stop
        uses: ./.github/workflows/actions/deploy_action
        with:
          discord-pub-key: ${{ secrets.DISCORD_PUB_KEY }}
          lol-api-key: ${{ secrets.LOL_API_KEY }}
          aws-secret: ${{ secrets.AWS_SECRET }}
          aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}

# Only one build at a time
concurrency: 
  group: main
  cancel-in-progress: true
